"""initial schema

Revision ID: 02dc64568f70
Revises: 
Create Date: 2026-03-07 17:35:03.884676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dc64568f70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f1_constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constructor_ref', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constructor_ref')
    )
    op.create_table('f1_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_ref', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_ref')
    )
    op.create_table('f1_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('circuit_name', sa.String(length=100), nullable=False),
    sa.Column('race_name', sa.String(length=100), nullable=False),
    sa.Column('race_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', name='uq_f1_race_season_round')
    )
    op.create_index('ix_f1_races_season', 'f1_races', ['season'], unique=False)
    op.create_table('pl_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_ref', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_ref')
    )
    op.create_table('f1_driver_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['f1_drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['f1_races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'race_id', 'driver_id', name='uq_f1_standing_season_race_driver')
    )
    op.create_index('ix_f1_driver_standings_season', 'f1_driver_standings', ['season'], unique=False)
    op.create_table('f1_lap_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_seconds', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['f1_drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['f1_races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_f1_lap_times_race_driver', 'f1_lap_times', ['race_id', 'driver_id'], unique=False)
    op.create_index('ix_f1_lap_times_season', 'f1_lap_times', ['season'], unique=False)
    op.create_table('pl_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_match_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['pl_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['pl_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_match_id')
    )
    op.create_index('ix_pl_matches_date', 'pl_matches', ['match_date'], unique=False)
    op.create_index('ix_pl_matches_season', 'pl_matches', ['season'], unique=False)
    op.create_table('pl_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['pl_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round', 'team_id', name='uq_pl_standing_season_round_team')
    )
    op.create_index('ix_pl_standings_season', 'pl_standings', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pl_standings_season', table_name='pl_standings')
    op.drop_table('pl_standings')
    op.drop_index('ix_pl_matches_season', table_name='pl_matches')
    op.drop_index('ix_pl_matches_date', table_name='pl_matches')
    op.drop_table('pl_matches')
    op.drop_index('ix_f1_lap_times_season', table_name='f1_lap_times')
    op.drop_index('ix_f1_lap_times_race_driver', table_name='f1_lap_times')
    op.drop_table('f1_lap_times')
    op.drop_index('ix_f1_driver_standings_season', table_name='f1_driver_standings')
    op.drop_table('f1_driver_standings')
    op.drop_table('pl_teams')
    op.drop_index('ix_f1_races_season', table_name='f1_races')
    op.drop_table('f1_races')
    op.drop_table('f1_drivers')
    op.drop_table('f1_constructors')
    # ### end Alembic commands ###
